### PR TITLE
miners: Show current total

### PR DESCRIPTION
**Pull request by tomat**
Only shows green %

### CODE REVIEW

**Comment by tomat** [comment]
image
image

**Comment by hsjoberg** [comment]
Thank you for your pull request @tomat.
Looks good to me, tested ACK f4e4f708c8d29fa49700d6c9782b10026581775f.

The code needs to be formatted by Prettier first before deployment though.

**Comment by tomat** [comment]
That should've fixed the formattting

**Comment by hsjoberg** [comment]
Awesome! LGTM. 💯

**Pull request merged**
