### PR TITLE
Update miner identifiers

### PR DESCRIPTION
**Pull request by coinforensics**
Updated some missing miners with the help of the search engine of your choice and the [pools.json](https://github.com/blockchain/Blockchain-Known-Pools/blob/master/pools.json) list from Blockchain.com.

### CODE REVIEW

**Comment by hsjoberg** [comment]
Thank you for your pull request @coinforensics! 💯

The list of mining pools is copied from https://github.com/0xB10C/known-mining-pools.
To make sure we're not differing from the upsteam project, could you do a pull request there as well?

**Comment by coinforensics** [comment]
I created a pull request there: https://github.com/0xB10C/known-mining-pools/pull/41

**Comment by hsjoberg** [comment]
@coinforensics Awesome to see your PR getting merged upstream! 💯  Could you pull the latest version from them to this PR instead of the current change-set?

**Comment by coinforensics** [comment]
@hsjoberg done

I removed the website for ArkPool again because it is still not merged in upstream.

**Comment by hsjoberg** [comment]
Thank you!
utACK.

**Pull request merged**
